### ISSUE TITLE
Food central API  500 error on any request to search endpoint 

### ISSUE THREAD

**Issue by sas604** [USDA/USDA-APIs#101]
Any request to /api.nal.usda.gov/fdc/v1/foods/search  returns 500 "Internal Server Error","message":"None of the configured nodes are available"

**Comment by boloni225** [comment]
Yeah I noticed the same thing, search doesn't seem to work on the USDA site either. I'm wondering if it's under maintenance or if it's down altogether. I sent them a message yesterday.

**Comment by andreivladmatei** [comment]
unfortunately is not the first time :(

**Comment by boloni225** [comment]
> unfortunately is not the first time :(

How often have you seen it happen? I just made and released an app on the Playstore with the API. No complains though the database is free and there's tons of data.

**Comment by AdamWier** [comment]
Thanks for opening this. Same problem for over 24 hours. And I'm complaining just a little.... It is the government and our taxes after all, and not some guy's hobby project. Going down for a while is something that can happen, sure, but going on more than a day and no message on their site or anything...? Maybe no one's around on the weekend.

**Comment by littlebunch** [comment]
Make sure you log a help desk request for this as well https://nal.altarama.com/reft100.aspx?key=FoodData.

**Comment by AdamWier** [comment]
Thanks for the link! Done and done.

**Comment by micimize** [comment]
Here is the response from a [`/v1/foods/list` swagger request](https://app.swaggerhub.com/apis/fdcnal/food-data_central_api/1.0.0#/FDC/getFoodsList):
```json
{
  "timestamp": "2020-09-27T20:30:48.396+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "None of the configured nodes are available: [{#transport#-1}{mehEJHwZRAqioQi-9UxMdg}{fdc-node1-azure.nal.usda.gov}{10.9.246.12:9300}, {#transport#-2}{0-HGvlpWTFe0UzNGyISANA}{fdc-node2-azure.nal.usda.gov}{10.9.246.13:9300}]",
  "path": "/portal-data/api/v1/foods/list"
}
```
```http
Response headers
 access-control-allow-methods: POST GETOPTIONS 
 access-control-allow-origin: * 
 age: 461 
 cache-control: no-cache 
 content-length: 364 
 content-type: application/json;charset=UTF-8 
 date: Sun27 Sep 2020 20:38:30 GMT 
 etag: W/"16c-DvixKlDVx3fYrEuI8oVxTjMWQcc" 
 expires: -1 
 server: nginx/1.18.0 + Phusion Passenger 6.0.6 
 status: 500500 Internal Server Error 
 strict-transport-security: max-age=63072000; includeSubDomains; preloadmax-age=31536000; includeSubDomains; preload 
 via: https/1.1 api-umbrella (ApacheTrafficServer [cMsSf ]) 
 x-cache: MISS 
 x-powered-by: ExpressPhusion Passenger 6.0.6 
```

**Comment by hphungnal** [comment]
@micimize @andreimateiro @AdamWier @boloni225 @littlebunch Apologies for the inconvenience! The site and API should be up and running again now. It seems that the Elasticsearch nodes went down at the start of the weekend. And yes, unfortunately, we do not have staff monitoring over the weekend.

**Comment by AdamWier** [comment]
Thank you for the update and your hard work! :)
