### ISSUE TITLE
api data structures formal description anywhere ?

### ISSUE THREAD

**Issue by ish-1313** [USDA/USDA-APIs#103]
Hello, 

Is there is anywhere formal description of api request/response structures ? there are some differences between samples and descriptions here and real life . few examples. 
in search request description "requireAllWords" not shown 
in search response .. in example "publicationDate": "4/1/2019"
but in real life "publishedDate": "2019-12-06"  ( i am talking about field name, not field value for sure ) 
you may check it with food "gtinUpc": "041303020937" 
this food used in samples for search get/post 

tia 
ish

**Comment by hphungnal** [comment]
@ish-1313 Yes, the current documentation for the API is at: https://fdc.nal.usda.gov/api-spec/fdc_api.html
For "requireAllWords" - this is a deprecated functionality. It is still returning in real life to not break legacy users, but this is why the documentation does not list it.
For "publishedDate" - you are correct that there is a mismatch between the documentation and implementation. We will fix this. Thank you!

**Comment by ish-1313** [comment]
> 
> 
> @ish-1313 Yes, the current documentation for the API is at: https://fdc.nal.usda.gov/api-spec/fdc_api.html
> For "requireAllWords" - this is a deprecated functionality. It is still returning in real life to not break legacy users, but this is why the documentation does not list it.
> For "publishedDate" - you are correct that there is a mismatch between the documentation and implementation. We will fix this. Thank you!

thank you. 
requireallwords: as api documentation refer this link https://fdc.nal.usda.gov/help.html#bkmk-2 for a search operators and requireallwords mentioned there, may be it worth to mention inside api docs that this feature is depreciated. i found it reading this link. i found it in server response so i decided that it just missed from api docs and implement it in a brand new code :)

one additional question  if you pls (or i can open new issue if need be ) 
from here : https://api.data.gov/docs/rate-limits/  i was trying to find X-RateLimit-Limit and X-RateLimit-Remaining  in response headers but there is no one. you didn't use them ?
