### ISSUE TITLE
AMS Excel download

### ISSUE THREAD

**Issue by sigwo** [USDA/USDA-APIs#107]
![image](https://user-images.githubusercontent.com/205676/97823842-ca932f80-1c7f-11eb-89ea-43d7963895b6.png)
Is there a way to pull this file via URL? I would like to schedule pulls and import into my database. Thanks.

**Comment by KyleMcKillop-USDA** [comment]
@sigwo Can you provide the website from this screenshot?  It does not look like it is from FDC and I will likely need to forward you do a different contact.

**Comment by sigwo** [comment]
https://organic.ams.usda.gov/integrity/Search.aspx
Or, who may I ask to have my API Key's limit raised from 1,000 per hour to 50,000 per hour?

**Comment by hphungnal** [comment]
@sigwo It seems like you can try emailing INTEGRITY@usda.gov. 

Sorry to not be of more help - AMS is a different agency in USDA than the one that Kyle and myself are a part of (ARS).

**Comment by sigwo** [comment]
Awesome! Thanks for the info :)
