### ISSUE TITLE
11-11-2020 . whole day problems with access to fdc via web and API

### ISSUE THREAD

**Issue by ish-1313** [USDA/USDA-APIs#109]
Hi, 

today we experience various problems with access to database via api or browser .  timeouts, product not found, error during search, bad gateway etc 

may be there is some information about estimated time of restoring normal access

tia 
ish
![image](https://user-images.githubusercontent.com/45285052/98825578-b43a6000-2445-11eb-83de-3c065a5596ca.png)

**Comment by ish-1313** [comment]
calling foods/search

`<!DOCTYPE html>\n<html>\n<head>\n<title>Error</title>\n<style>\n    body {\n        width: 35em;\n        margin: 0 auto;\n        font-family: Tahoma, Verdana, Arial, sans-serif;\n    }\n</style>\n</head>\n<body>\n<h1>An error occurred.</h1>\n<p>Sorry, the page you are looking for is currently unavailable.<br/>\nPlease try again later.</p>\n<p>If you are the system administrator of this resource then you should check\nthe error log for details.</p>\n<p><em>Faithfully yours, nginx.</em></p>\n</body>\n</html>\n`

**Comment by hphungnal** [comment]
@ish-1313 Please try again now. There was a hiccup on one of the servers but it should be resolved now.

**Comment by ish-1313** [comment]
> 
> 
> @ish-1313 Please try again now. There was a hiccup on one of the servers but it should be resolved now.

seems better .. but some search results returns error on product details loading (never see such errors before today )
few samples 

![image](https://user-images.githubusercontent.com/45285052/98838825-d50ab180-2455-11eb-84bb-4d70f1da6e8a.png)
![image](https://user-images.githubusercontent.com/45285052/98838889-e9e74500-2455-11eb-8414-2e8810a20758.png)
![image](https://user-images.githubusercontent.com/45285052/98838930-f53a7080-2455-11eb-864a-a2a4e24cdd50.png)

**Comment by hphungnal** [comment]
@ish-1313 Apologies for the inconvenience. We had tried to optimize some DB caching and that unfortunately had a side effect on these foods (and some others) not being fetched correctly. The updates have been reverted for now so it should be all good again. I checked all 3 of these foods you pasted and they are working now.

**Comment by ish-1313** [comment]
thank you :) dealing with this i understood that search data is enough for me :)
closing
