### ISSUE TITLE
Where can I find monthly branded foods dataset?

### ISSUE THREAD

**Issue by hhimanshu** [USDA/USDA-APIs#123]
Hello,

As per [this documentation](https://fdc.nal.usda.gov/data-documentation.html), the **Update Frequency** for _Branded Foods_ is `Monthly`.
However, on the [`Downloads`](https://fdc.nal.usda.gov/download-datasets.html) page, the latest link available for _Branded Foods_ is from `Oct 2022`.

As we are in `Apr 2023`, I wanted to check if there is another location where I should look for Monthly _Branded Foods_ download links.

Thank you

**Comment by hhimanshu** [comment]
Hello, 

Could someone please help?

**Comment by jamesallain** [comment]
The [api](https://fdc.nal.usda.gov/api-guide.html) might be updated monthly, but the [downloads](https://fdc.nal.usda.gov/download-datasets.html) are only updated every 3 to 6 months in seems.

**Comment by hhimanshu** [comment]
I see. thanks for the update, @jamesallain
