### ISSUE TITLE
Farmers Markets producing invalid JSON

### ISSUE THREAD

**Issue by JustinLove** [USDA/USDA-APIs#2]
JSON parse throws up on trailing comma.

http://search.ams.usda.gov/FarmersMarkets/v1/data.svc/zipSearch?zip=99501

``` javascript
{
    "results": [
        {
            "id": "21002227",
            "marketname": "0.8 Anchorage Market & Festival"
        },
.....
       {
            "id": "1003446",
            "marketname": "78.7 Tustumena Farmer's Market"
        },

    ]
}
```

**Comment by msd101psu** [comment]
This invalid JSON was caused by a bug, which has been corrected.

**Comment by ShaylaMae** [comment]
Thanks for bringing this to our attention, Justin. We believe it's been resolved, but please let us know if the issue persists.
