### ISSUE TITLE
HTTP 404 when calling the API

### ISSUE THREAD

**Issue by cathwaggoner** [USDA/USDA-APIs#3]
I am trying to do a basic http request to the API using a Curl like tool called Postman.  I copied and pasted the URL from the documentation for a zipSearch.  I provided the query parameter zip and gave it a valid zip.  I also set the Content-Type header to application/json;  charset=utf-8.  The server is returning an HTTP 404 though.  

Hereis the URL I am using:
http://search.ams.usda.gov/v1/data.svc/zipSearch?zip=94612

**Comment by amandare** [comment]
Hello - The sample URLs did not reflect the API move to production.  You should be able to use this URL instead:

http://search.ams.usda.gov/farmersmarkets/v1/data.svc/zipSearch?zip=94612

AMS has updated the API code examples to reflect the directory structure change.

**Comment by ShaylaMae** [comment]
@cathwaggoner -- did that resolve the issue for you?

**Comment by cathwaggoner** [comment]
It did, thank you! Really awesome to have all of this information in one
place. Do you have plans to release anymore APIs around food and farming?

best,

Catherine

**Comment by ShaylaMae** [comment]
Glad to hear that worked for you and thanks for the feedback on our data set.  At our agency (the Agricultural Marketing Service), we're looking at our other online data sets, with the goal of releasing more APIs in the future.  We have things like lists of certified organic operations, food/commodity pricing information, etc, that we collect.  We don't have a specific timeline for the next one(s) yet, though.  USDA as a whole has other APIs available at http://www.usda.gov/developers.  You might want to check them out.
