### ISSUE TITLE
405 Error for JSON Request for JavaScript Service Request

### ISSUE THREAD

**Issue by april-lundy** [USDA/USDA-APIs#4]
Apparently, the service is missing some header values that allow cross-domain requests. You can directly request the service via a browser, but an AJAX request fails. Has anyone else seen this issue?

**Comment by april-lundy** [comment]
For later readers: Note that you can add a dataType: 'jsonp' to the $.ajax call to allow the cross domain request.

**Comment by april-lundy** [comment]
Spoke too soon. It seems that the server doesn't allow JSONP requests? Any suggestions?

**Comment by msd101psu** [comment]
The server now allows JSONP requests.

**Comment by ShaylaMae** [comment]
We believe this issue has been resolved.  Please let us know if the issue persists.
