### ISSUE TITLE
Quick Stats api not working

### ISSUE THREAD

**Issue by aaru** [USDA/USDA-APIs#42]
Quick Stats api listed in http://www.usda.gov//wps/portal/usda/usdahome?navid=USDA_DEVELOPER is not working.
API Details:-
Quick Stats : http://quickstats.nass.usda.gov/api

**Comment by bbrotsos** [comment]
What specific issues are you having problems with the API?  Have you used this API before?

**Comment by aaru** [comment]
thanks, its fine now.. looks like server was down when i tried
