### ISSUE TITLE
Is it possible to get the link to the food report?

### ISSUE THREAD

**Issue by petermorlion** [USDA/USDA-APIs#45]
Doing an API call for nutritional data gives me a response that contains the ndbno. However, I cannot construct a URL that links to the food report page of this ndbno.

For example, the food report of ndbno 14532 is this url:

```
https://ndb.nal.usda.gov/ndb/foods/show/4416
```

So ndbno 14532 maps to some number (the internal id?) 4416. Is it possible to retrieve these numbers?

**Comment by littlebunch** [comment]
You should  be able to construct a URL like this:
https://ndb.nal.usda.gov/ndb/foods/show?ndbno={ndbno}&rptfrm=nl
e.g.
https://ndb.nal.usda.gov/ndb/foods/show?ndbno=09427&rptfrm=nl
HTH
