### ISSUE TITLE
Food Composition API is down

### ISSUE THREAD

**Issue by cattrae** [USDA/USDA-APIs#53]
There is an outage on the Food Composition API.  
And the site describing documentation is also down: https://ndb.nal.usda.gov/ndb/doc/index

Will the API be back up and running anytime soon?

**Comment by littlebunch** [comment]
Unofficial word is that there is an AT&T WAN circuit down preventing any communication outside the Beltsville MD campus.  At this point there is no ETC for a return of service.

**Comment by upieper** [comment]
The network issue has been solved yesterday afternoon. Please let us know if you still experience any problems.

**Comment by cattrae** [comment]
Great, thank you!
