### ISSUE TITLE
Querying FoodData Central with Python Requests

### ISSUE THREAD

**Issue by noahtren** [USDA/USDA-APIs#64]
Hi all,

Really excited to work with the new data available from FDC, the Foundational Foods Dataset looks especially interesting. I have been working on a Python package recently that interfaces with the Standard Reference Database and would like to try extending its access to Foundational Foods.

The FDC website gives examples for how to implement the `curl` command to interface with the API, but I am having trouble transcribing this to Python requests.

For example, the follow request gets an error response:
```python
params = {"generalSearchInput":"almond", "api_key":API_KEY}
response = (requests.get(url="https://api.nal.usda.gov/fdc/v1/search", params=params).json)
```
This returns
```
{'timestamp': '2019-04-04T20:45:15.257+0000', 'status': 400, 'error': 'Bad Request', 'message': 'Failed to convert value of type \'java.lang.String\' to required type \'java.lang.Long\'; nested exception is java.lang.NumberFormatException: For input string: "search"', 'path': '/portal-data/api/v1/search'}
```

**Comment by littlebunch** [comment]
Trying issuing your search requests as a POST — not documented (yet) but JSON passed as a parameter hardly ever works.  You will also need to send your api key in the header as an x-api-key  token or as a GET query parameter or as a username like in basic auth, i.e. https://API_KEY@api.nal.usda.gov/fdc <https://API_KEY@api.nal.usda.gov/fdc> …. etc.  See https://api.data.gov/docs/api-key <https://api.data.gov/docs/api-key> 
HTH
Gary

**Comment by noahtren** [comment]
Hi, thanks for the help!
I've set up the search request as a POST and have assigned the api key as a header. I am now getting a different error which I'm suspecting may be due to JSON not working?
```python
target_url = "https://api.nal.usda.gov/fdc/v1/search"
params = {'generalSearchInput':'almond'}
headers = {"x-api-key":API_KEY}
response = requests.post(target_url, headers=headers, data=params).json()
```
```
{'timestamp': '2019-04-05T15:09:52.575+0000', 'status': 415, 'error': 'Unsupported Media Type', 'message': "Content type 'application/x-www-form-urlencoded;charset=UTF-8' not supported", 'path': '/portal-data/api/v1/search'}
```

**Comment by littlebunch** [comment]
I’m not a python programmer, you might need to add a “Content-type: application/json” header.
Gary

**Comment by 1FootN** [comment]
> Hi, thanks for the help!
> I've set up the search request as a POST and have assigned the api key as a header. I am now getting a different error which I'm suspecting may be due to JSON not working?
> 
> ```python
> target_url = "https://api.nal.usda.gov/fdc/v1/search"
> params = {'generalSearchInput':'almond'}
> headers = {"x-api-key":API_KEY}
> response = requests.post(target_url, headers=headers, data=params).json()
> ```
> 
> ```
> {'timestamp': '2019-04-05T15:09:52.575+0000', 'status': 415, 'error': 'Unsupported Media Type', 'message': "Content type 'application/x-www-form-urlencoded;charset=UTF-8' not supported", 'path': '/portal-data/api/v1/search'}
> ```

noahtren-did you ever figure this out, I've been trying too, but haven't figured it yet

**Comment by sdouma** [comment]
I would close this issue.

**Comment by noahtren** [comment]
Revisiting this problem after a long time and found the solution. Firstly, it needs to be a POST request instead of GET as @littlebunch mentions. The extra step is to pass the main body of the request with the `json` parameter, instead of passing everything to `params`.

```python
params = {'api_key': key}
data = {'generalSearchInput': 'chia'}
response = requests.post(
    r'https://api.nal.usda.gov/fdc/v1/search',
    params=params,
    json=data
)
print(response.json())
```
