### ISSUE TITLE
How do I get more than 1 page of 50 food items per search?

### ISSUE THREAD

**Issue by SteveCEms** [USDA/USDA-APIs#84]
I'm doing 3 api gets to find up to 150 food items for each request. How can I get more than 50 food items per search? Is there a way to set pageNumber=1-3 or something similar to get up to 3 pages of results.

**Comment by littlebunch** [comment]
@SteveCEms Yeah, I think my proposed [spec](https://github.com/USDA/USDA-APIs/issues/800) adds a "limit" parameter which would allow you to request 1 to MAX_DOC_SIZE.  Hopefully that gets into the next release.  Certainly 150 documents is a reasonable MAX_DOC_SIZE.  I'd probably like a higher number, i.e. 1,500.

**Comment by SteveCEms** [comment]
I limited to 150 in the old api and told the user to add more search terms to his search. It takes a long time to scroll through even 150 lines that may have folded on a small phone screen. Adding a limit parameter would mean I wouldn't have to search 3 times for most searches to get at least 150 food items.

**Comment by SteveCEms** [comment]
@littlebunch When is the next release?

**Comment by SteveCEms** [comment]
The new api has a pageSize value that allows me to do 1 search and get a page size of 150 food items. I consider this issue closed. Thanks @littlebunch .
