### ISSUE TITLE
Are all foods in FDC database standarised?

### ISSUE THREAD

**Issue by ghost** [USDA/USDA-APIs#95]
My app assumes that serving size is always 100 grams, protein is always returned in grams, copper is always in mg, phosphorus in mg etc. My question is - Am I right? Becouse I'm worried that my app will misrepresent particular foods. The API returns unit name of every nutrient so I'm propably wrong, unfortunetly, but I need official info regarding this. I didn't found any food to be returned in other way - even salt is given in 100 grams of serving size

**Comment by littlebunch** [comment]
I know all nutrient amounts for the branded food data type are 100g equivalents as explained in the [documentation](https://fdc.nal.usda.gov/docs/BFPDB_Doc_Aug2018.pdf).  You need to check the [documentation](https://fdc.nal.usda.gov/data-documentation.html) for other data types or send a query to the [help desk](https://nal.altarama.com/reft100.aspx?pmi=TEq508xjIq).

**Comment by jedzoka** [comment]
Okay, I got an clear answer https://nal.altarama.com/reft205.aspx?pmi=sykmbXKbg8
